import os
import warnings
import logging

# Silence all verbose PyTorch/transformers path access warnings globally
os.environ["TRANSFORMERS_VERBOSITY"] = "error"
os.environ["PYTHONWARNINGS"] = "ignore"
warnings.filterwarnings("ignore")
logging.getLogger("transformers").setLevel(logging.ERROR)

import streamlit as st
import os
import sys
from datetime import datetime
import importlib

# Add the project root to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from memory.chroma_store import get_all_memories
from frontend.shared_theme import apply_shared_theme

st.set_page_config(
    page_title="Nexus | AI Memory Bank",
    page_icon="🧠",
    layout="wide"
)

# Apply global premium SaaS theme & sidebar widgets
apply_shared_theme()

# Header
st.markdown("""
<div class="header-card header-card-memory">
    <h1 style="font-weight: 700; font-size: 2.5rem; margin-bottom: 10px; color: #ffffff; display: flex; align-items: center; gap: 15px;">
        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#34d399" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/></svg>
        AI Memory Bank
    </h1>
    <p style="color: #a1a1aa; font-size: 1.1rem; margin: 0;">
        Browse the autonomous vector database. All research generated by Nexus Agents is permanently indexed here for semantic retrieval.
    </p>
</div>
""", unsafe_allow_html=True)

try:
    memories = get_all_memories()
    
    if not memories:
        st.markdown("""
        <div style="text-align: center; padding: 40px; background: rgba(255,255,255,0.02); border-radius: 12px; border: 1px dashed rgba(255,255,255,0.1); margin-top: 30px;">
            <p style="color: #71717a; font-size: 1.1rem; margin: 0;">
                The AI Memory Bank is currently empty. Execute a research protocol on the home page to populate the database.
            </p>
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown(f"<p style='color: #34d399; font-weight: 600; margin-bottom: 20px;'>{len(memories)} Encoded Memories Found</p>", unsafe_allow_html=True)
        
        for mem in memories:
            meta = mem['metadata']
            topic = meta.get('topic', 'Unknown Topic')
            
            # Try to format the timestamp nicely
            raw_time = meta.get('timestamp', '')
            try:
                dt = datetime.fromisoformat(raw_time)
                formatted_time = dt.strftime("%B %d, %Y at %I:%M %p")
            except:
                formatted_time = raw_time
            
            # Render each memory as an expander
            with st.expander(f"📁 {topic}"):
                st.markdown(f"<div class='memory-tag'>Recorded: {formatted_time}</div>", unsafe_allow_html=True)
                
                # The document contains the combined Summary, Critic, and Full Research from the memory_manager
                st.markdown("### Raw Vector Data")
                st.markdown(mem['document'])
                
                st.markdown(f"<p style='font-size: 0.8rem; color: #71717a; margin-top: 20px;'>UUID: {mem['id']}</p>", unsafe_allow_html=True)

except Exception as e:
    st.error("Failed to connect to ChromaDB Vector Store. Ensure dependencies are installed and the database isn't locked.")
    st.code(str(e))
