import os
import warnings
import logging

# Silence all verbose PyTorch/transformers path access warnings globally
os.environ["TRANSFORMERS_VERBOSITY"] = "error"
os.environ["PYTHONWARNINGS"] = "ignore"
warnings.filterwarnings("ignore")
logging.getLogger("transformers").setLevel(logging.ERROR)

import streamlit as st
import os
import sys
import re
import json
import ast
from datetime import datetime
import importlib

# Add the project root to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

def parse_memory_document(doc_text):
    sections = {}
    
    # Locate section headers
    summary_idx = doc_text.find("SUMMARY:\n")
    critique_idx = doc_text.find("CRITIQUE:\n")
    research_idx = doc_text.find("FULL RESEARCH:\n")
    
    if summary_idx != -1 and critique_idx != -1 and research_idx != -1:
        sections['topic'] = doc_text[:summary_idx].replace("TOPIC:", "").strip()
        sections['summary'] = doc_text[summary_idx:critique_idx].replace("SUMMARY:\n", "").strip()
        sections['critique'] = doc_text[critique_idx:research_idx].replace("CRITIQUE:\n", "").strip()
        sections['full_research'] = doc_text[research_idx:].replace("FULL RESEARCH:\n", "").strip()
    else:
        # Fallback if the markers are not present
        sections['raw'] = doc_text
        
    return sections

def parse_critique_dict(critique_str):
    critique_str = critique_str.strip()
    # Try parsing string representation of Python dict
    try:
        return ast.literal_eval(critique_str)
    except Exception:
        pass
    
    # Try parsing JSON
    try:
        return json.loads(critique_str)
    except Exception:
        pass
        
    # Search for json/dict block in case of wrapping or extra text
    try:
        match = re.search(r'\{.*\}', critique_str, re.DOTALL)
        if match:
            return ast.literal_eval(match.group(0))
    except Exception:
        pass
        
    try:
        match = re.search(r'\{.*\}', critique_str, re.DOTALL)
        if match:
            return json.loads(match.group(0))
    except Exception:
        pass
        
    return None

from memory.chroma_store import get_all_memories
from frontend.shared_theme import apply_shared_theme

st.set_page_config(
    page_title="Nexus | AI Memory Bank",
    page_icon="🧠",
    layout="wide"
)

# Apply global premium SaaS theme & sidebar widgets
apply_shared_theme()

active_ws = st.session_state.get("active_workspace", "default")

# Header
st.markdown(f"""
<div class="header-card header-card-memory">
    <h1 style="font-weight: 700; font-size: 2.5rem; margin-bottom: 10px; color: #ffffff; display: flex; align-items: center; gap: 15px;">
        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#34d399" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/></svg>
        AI Memory Bank — {active_ws.upper()}
    </h1>
    <p style="color: #a1a1aa; font-size: 1.1rem; margin: 0;">
        Browse the autonomous vector database for active workspace <strong style="color: #34d399;">{active_ws.upper()}</strong>. All research generated by Nexus Agents is permanently indexed here for semantic retrieval.
    </p>
</div>
""", unsafe_allow_html=True)

try:
    memories = get_all_memories(workspace=active_ws)
    
    if not memories:
        st.markdown(f"""
        <div style="text-align: center; padding: 40px; background: rgba(255,255,255,0.02); border-radius: 12px; border: 1px dashed rgba(255,255,255,0.1); margin-top: 30px;">
            <p style="color: #71717a; font-size: 1.1rem; margin: 0;">
                The AI Memory Bank is currently empty in workspace '{active_ws}'. Execute a research protocol on the home page to populate the database.
            </p>
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown("""
        <style>
        /* Reset global tab styles for the memory bank page to use clean emojis instead */
        div[data-testid="stTabBar"] button[role="tab"] p::before,
        div[data-testid="stTabBar"] button[role="tab"] span::before,
        div[data-testid="stTabs"] button[role="tab"] p::before,
        div[data-testid="stTabs"] button[role="tab"] span::before {
            display: none !important;
            content: none !important;
            background-image: none !important;
        }
        div[data-testid="stTabBar"] button[role="tab"] p,
        div[data-testid="stTabBar"] button[role="tab"] span,
        div[data-testid="stTabs"] button[role="tab"] p,
        div[data-testid="stTabs"] button[role="tab"] span {
            padding-left: 0px !important;
        }
        </style>
        """, unsafe_allow_html=True)
        st.markdown(f"<p style='color: #34d399; font-weight: 600; margin-bottom: 20px;'>{len(memories)} Encoded Memories Found</p>", unsafe_allow_html=True)
        
        for mem in memories:
            meta = mem['metadata']
            topic = meta.get('topic', 'Unknown Topic')
            
            # Try to format the timestamp nicely
            raw_time = meta.get('timestamp', '')
            try:
                dt = datetime.fromisoformat(raw_time)
                formatted_time = dt.strftime("%B %d, %Y at %I:%M %p")
            except:
                formatted_time = raw_time
            
            # Render each memory as an expander
            with st.expander(f"🗂  Memory: {topic[:55]}{'...' if len(topic) > 55 else ''}"):
                # Rich Lucide icon title row inside (showing full topic)
                st.markdown(
                    f"<div style='display:flex;align-items:center;gap:12px;"
                    f"padding:12px 16px;margin-bottom:14px;"
                    f"background:rgba(52,211,153,0.07);"
                    f"border-radius:10px;border:1px solid rgba(52,211,153,0.18);'>"
                    # Folder icon
                    f"<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' viewBox='0 0 24 24' fill='none' stroke='#34d399' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                    f"<path d='M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z'/>"
                    f"</svg>"
                    f"<div style='flex:1;min-width:0;'>"
                    f"<p style='margin:0;font-size:0.7rem;font-weight:700;text-transform:uppercase;"
                    f"letter-spacing:0.1em;color:#34d399;'>Encoded Memory Record</p>"
                    f"<p style='margin:2px 0 0 0;font-size:0.95rem;font-weight:600;color:#ffffff;"
                    f"line-height:1.4;'>{topic}</p>"
                    f"</div>"
                    f"</div>",
                    unsafe_allow_html=True
                )
                
                # Badge row with Lucide icons
                st.markdown(
                    f"<div style='display:flex; gap:10px; margin-bottom:20px; flex-wrap:wrap;'>"
                    # Clock icon badge
                    f"<span style='display:inline-flex;align-items:center;gap:6px;"
                    f"background:rgba(52,211,153,0.1);color:#34d399;"
                    f"padding:5px 12px;border-radius:20px;font-size:0.8rem;"
                    f"border:1px solid rgba(52,211,153,0.3);font-weight:600;'>"
                    f"<svg xmlns='http://www.w3.org/2000/svg' width='13' height='13' viewBox='0 0 24 24' fill='none' stroke='#34d399' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'/><polyline points='12 6 12 12 16 14'/></svg>"
                    f" {formatted_time}</span>"
                    # ID badge
                    f"<span style='display:inline-flex;align-items:center;gap:6px;"
                    f"background:rgba(255,255,255,0.05);color:#71717a;"
                    f"padding:5px 12px;border-radius:20px;font-size:0.8rem;'>"
                    f"<svg xmlns='http://www.w3.org/2000/svg' width='13' height='13' viewBox='0 0 24 24' fill='none' stroke='#71717a' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='4' width='18' height='18' rx='2' ry='2'/><line x1='16' y1='2' x2='16' y2='6'/><line x1='8' y1='2' x2='8' y2='6'/><line x1='3' y1='10' x2='21' y2='10'/></svg>"
                    f" ID: {mem.get('id', '—')}</span>"
                    f"</div>",
                    unsafe_allow_html=True
                )
                
                # Parse the combined document
                sections = parse_memory_document(mem['document'])
                
                if 'raw' in sections:
                    # Fallback if we couldn't parse the expected structure
                    st.markdown(sections['raw'])
                else:
                    # Render structured tabs
                    tab_sum, tab_crit, tab_res = st.tabs([
                        "📝 Executive Summary",
                        "🧐 Critic Analysis",
                        "🔬 Full Research Report"
                    ])
                    
                    with tab_sum:
                        st.markdown(sections['summary'])
                    with tab_crit:
                        crit_data = parse_critique_dict(sections['critique'])
                        if crit_data and isinstance(crit_data, dict):
                            # Beautiful custom HTML/CSS for critique
                            score = crit_data.get('score', 'N/A')
                            grade = crit_data.get('research_grade')
                            
                            grade_badge = f"<span style='background:rgba(251, 191, 36, 0.1); color:#fbbf24; border:1px solid rgba(251, 191, 36, 0.3); padding:4px 12px; border-radius:20px; font-size:0.85rem; font-weight:700;'>Grade: {grade}</span>" if grade else ""
                            
                            # Score badge/metric
                            st.markdown(f"""
                            <div style='display: flex; align-items: center; justify-content: space-between; background: rgba(239, 68, 68, 0.08); padding: 16px 24px; border-radius: 12px; border: 1px solid rgba(239, 68, 68, 0.15); margin-bottom: 20px;'>
                                <div style='display: flex; align-items: center; gap: 12px;'>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ef4444" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                                    <span style='font-size: 1.1rem; font-weight: 600; color: #ffffff;'>Critic Quality Assessment Score</span>
                                    {grade_badge}
                                </div>
                                <div style='font-size: 1.8rem; font-weight: 700; color: #ef4444;'>{score} <span style='font-size: 1rem; color: #a1a1aa;'>/ 10</span></div>
                            </div>
                            """, unsafe_allow_html=True)
                                       # Strengths and Weaknesses side by side
                            col_str, col_weak = st.columns(2)
                            
                            with col_str:
                                st.markdown("<p style='font-weight:700; color:#10b981; font-size:1.15rem; margin-bottom:12px; display:flex; align-items:center; gap:8px;'><svg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='#10b981' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'><polyline points='20 6 9 17 4 12'/></svg> Strengths</p>", unsafe_allow_html=True)
                                strengths = crit_data.get('strengths', [])
                                if strengths:
                                    for s in strengths:
                                        st.markdown(f"<div style='background:rgba(16, 185, 129, 0.04); border-left:3px solid #10b981; padding:8px 12px; border-radius:4px; margin-bottom:8px; color:#d4d4d8; font-size:0.95rem;'>{s}</div>", unsafe_allow_html=True)
                                else:
                                    st.write("None identified.")
                                    
                            with col_weak:
                                st.markdown("<p style='font-weight:700; color:#ef4444; font-size:1.15rem; margin-bottom:12px; display:flex; align-items:center; gap:8px;'><svg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='#ef4444' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'><line x1='18' y1='6' x2='6' y2='18'/><line x1='6' y1='6' x2='18' y2='18'/></svg> Weaknesses</p>", unsafe_allow_html=True)
                                weaknesses = crit_data.get('weaknesses', [])
                                if weaknesses:
                                    for w in weaknesses:
                                        st.markdown(f"<div style='background:rgba(239, 68, 68, 0.04); border-left:3px solid #ef4444; padding:8px 12px; border-radius:4px; margin-bottom:8px; color:#d4d4d8; font-size:0.95rem;'>{w}</div>", unsafe_allow_html=True)
                                else:
                                    st.write("None identified.")
                            
                            # Quality & Coverage Assessments
                            q_assessment = crit_data.get('report_quality_assessment')
                            c_analysis = crit_data.get('coverage_analysis')
                            if q_assessment or c_analysis:
                                col_q, col_c = st.columns(2)
                                with col_q:
                                    if q_assessment:
                                        st.markdown("<p style='font-weight:700; color:#a5b4fc; font-size:1.1rem; margin-top:10px; margin-bottom:6px;'>Report Quality Assessment</p>", unsafe_allow_html=True)
                                        st.write(q_assessment)
                                with col_c:
                                    if c_analysis:
                                        st.markdown("<p style='font-weight:700; color:#a5b4fc; font-size:1.1rem; margin-top:10px; margin-bottom:6px;'>Coverage Analysis</p>", unsafe_allow_html=True)
                                        if isinstance(c_analysis, dict):
                                            for sec, val in c_analysis.items():
                                                st.markdown(f"<div style='font-size:0.9rem; margin-bottom:4px; color:#d4d4d8;'><strong>{sec}</strong>: {val}</div>", unsafe_allow_html=True)
                                        else:
                                            st.write(c_analysis)
 
                            # Accuracy & Completeness Assessments
                            a_assessment = crit_data.get('accuracy_assessment')
                            comp_assessment = crit_data.get('completeness_assessment')
                            if a_assessment or comp_assessment:
                                col_a, col_comp = st.columns(2)
                                with col_a:
                                    if a_assessment:
                                        st.markdown("<p style='font-weight:700; color:#a5b4fc; font-size:1.1rem; margin-top:10px; margin-bottom:6px;'>Accuracy Assessment</p>", unsafe_allow_html=True)
                                        st.write(a_assessment)
                                with col_comp:
                                    if comp_assessment:
                                        st.markdown("<p style='font-weight:700; color:#a5b4fc; font-size:1.1rem; margin-top:10px; margin-bottom:6px;'>Completeness Assessment</p>", unsafe_allow_html=True)
                                        st.write(comp_assessment)
 
                            # Missing areas
                            missing = crit_data.get('missing_research_areas', crit_data.get('missing_areas', crit_data.get('missing_topics', [])))
                            if missing:
                                st.markdown("<p style='font-weight:700; color:#f59e0b; font-size:1.15rem; margin-top:20px; margin-bottom:12px; display:flex; align-items:center; gap:8px;'><svg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='#f59e0b' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'/><line x1='12' y1='8' x2='12' y2='12'/><line x1='12' y1='16' x2='12.01' y2='16'/></svg> Missing Research Areas & Gaps</p>", unsafe_allow_html=True)
                                for m in missing:
                                    st.markdown(f"<div style='background:rgba(245, 158, 11, 0.04); border-left:3px solid #f59e0b; padding:8px 12px; border-radius:4px; margin-bottom:8px; color:#d4d4d8; font-size:0.95rem;'>{m}</div>", unsafe_allow_html=True)
                            
                            # Suggestions / Improvement Priorities
                            imp_priorities = crit_data.get('improvement_priorities', {})
                            suggestions = crit_data.get('improvement_recommendations', crit_data.get('improvement_suggestions', []))
                            
                            if imp_priorities and isinstance(imp_priorities, dict):
                                st.markdown("<p style='font-weight:700; color:#3b82f6; font-size:1.15rem; margin-top:20px; margin-bottom:12px; display:flex; align-items:center; gap:8px;'><svg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='#3b82f6' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'><path d='M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3'/><line x1='12' y1='17' x2='12.01' y2='17'/></svg> Improvement Priorities</p>", unsafe_allow_html=True)
                                for prio, items in imp_priorities.items():
                                    if items:
                                        prio_color = "#ef4444" if "High" in prio else ("#f59e0b" if "Medium" in prio else "#3b82f6")
                                        st.markdown(f"<p style='font-weight:800; color:{prio_color}; font-size:0.95rem; margin-top:8px; margin-bottom:4px;'>{prio}</p>", unsafe_allow_html=True)
                                        if isinstance(items, list):
                                            for item in items:
                                                st.markdown(f"<div style='background:rgba(59, 130, 246, 0.03); border-left:3px solid {prio_color}; padding:6px 12px; border-radius:4px; margin-bottom:6px; color:#d4d4d8; font-size:0.95rem;'>{item}</div>", unsafe_allow_html=True)
                                        else:
                                            st.markdown(f"<div style='background:rgba(59, 130, 246, 0.03); border-left:3px solid {prio_color}; padding:6px 12px; border-radius:4px; margin-bottom:6px; color:#d4d4d8; font-size:0.95rem;'>{items}</div>", unsafe_allow_html=True)
                            elif suggestions:
                                st.markdown("<p style='font-weight:700; color:#3b82f6; font-size:1.15rem; margin-top:20px; margin-bottom:12px; display:flex; align-items:center; gap:8px;'><svg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='#3b82f6' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'><path d='M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3'/><line x1='12' y1='17' x2='12.01' y2='17'/></svg> Improvement Recommendations</p>", unsafe_allow_html=True)
                                for su in suggestions:
                                    st.markdown(f"<div style='background:rgba(59, 130, 246, 0.04); border-left:3px solid #3b82f6; padding:8px 12px; border-radius:4px; margin-bottom:8px; color:#d4d4d8; font-size:0.95rem;'>{su}</div>", unsafe_allow_html=True)
                            
                            # Confidence level & verdict
                            conf = crit_data.get('confidence_level')
                            verdict = crit_data.get('final_verdict')
                            if conf:
                                st.markdown(f"<p style='font-weight:700; color:#818cf8; font-size:1.1rem; margin-top:20px; margin-bottom:6px;'>Confidence Level</p>", unsafe_allow_html=True)
                                st.write(conf)
                            if verdict:
                                st.markdown(f"<p style='font-weight:700; color:#fb7185; font-size:1.1rem; margin-top:20px; margin-bottom:6px;'>Final Verdict</p>", unsafe_allow_html=True)
                                st.write(verdict)
 
                            # Clarity (for older records)
                            clarity = crit_data.get('clarity_evaluation', '')
                            if clarity:
                                st.markdown("<p style='font-weight:700; color:#ec4899; font-size:1.15rem; margin-top:20px; margin-bottom:12px; display:flex; align-items:center; gap:8px;'><svg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='#ec4899' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'><path d='M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z'/><path d='M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z'/></svg> Clarity & Tone Evaluation (Legacy)</p>", unsafe_allow_html=True)
                                st.markdown(f"<div style='background:rgba(236, 72, 153, 0.04); border-left:3px solid #ec4899; padding:12px; border-radius:4px; color:#d4d4d8; font-size:0.95rem; line-height:1.6;'>{clarity}</div>", unsafe_allow_html=True)
                        else:
                            st.markdown(sections['critique'])
                            
                    with tab_res:
                        st.markdown(sections['full_research'])

except Exception as e:
    st.error("Failed to connect to ChromaDB Vector Store. Ensure dependencies are installed and the database isn't locked.")
    st.code(str(e))
