import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.researcher_agent import refine_research
from agents.critic_agent import critique_research
from agents.summarizer_agent import summarize_research

def run_optimization_loop(topic: str, initial_report: str) -> dict:
    """
    Manages the iterative self-correction feedback loop.
    
    Workflow:
    1. Summarize initial report (needed for Critic)
    2. Critique initial report (v1)
    3. Evaluate score. If high enough, return v1.
    4. Inject feedback and refine research (v2).
    5. Summarize v2.
    6. Critique v2.
    7. Compare scores, return the best version.
    
    Args:
        topic (str): The research topic.
        initial_report (str): The v1 markdown report generated by the Researcher Agent.
        
    Returns:
        dict: {
            "final_report": str,
            "final_summary": str,
            "final_critique": dict,
            "original_critique": dict,
            "optimized": bool,
            "score_delta": float
        }
    """
    print("\n" + "="*50)
    print("[Loop Controller] Initiating Self-Correction Pipeline")
    print("="*50)
    
    # ── Step 1: Initial Summary & Critique ──────────────────────────────
    print("[Loop Controller] Generating v1 summary for Critic...")
    initial_summary = summarize_research(initial_report)
    if initial_summary.startswith("⚠️"):
        return _fallback_result(initial_report, initial_summary, {"error": "Summarizer failed."})

    print("[Loop Controller] Evaluating v1 report...")
    initial_critique = critique_research(initial_report, initial_summary)
    
    if "error" in initial_critique:
        print("[Loop Controller Error] Critic Agent failed on v1. Aborting optimization.")
        return _fallback_result(initial_report, initial_summary, initial_critique)
        
    initial_score = float(initial_critique.get("score", 0.0))
    print(f"[Loop Controller] Initial Critic Score: {initial_score}/10")
    
    # Optional threshold: If it's already amazing, don't waste tokens
    if initial_score >= 9.0:
        print("[Loop Controller] Report quality is already exceptional. Skipping refinement.")
        return {
            "final_report": initial_report,
            "original_report": initial_report,
            "final_summary": initial_summary,
            "final_critique": initial_critique,
            "original_critique": initial_critique,
            "optimized": False,
            "score_delta": 0.0
        }
        
    # ── Step 2: Refinement ──────────────────────────────────────────────
    print("\n[Loop Controller] Injecting feedback & triggering refinement...")
    optimized_report = refine_research(topic, initial_report, initial_critique)
    
    if optimized_report.startswith("⚠️"):
        print("[Loop Controller Error] Refinement failed. Falling back to v1.")
        return _fallback_result(initial_report, initial_summary, initial_critique)
        
    # ── Step 3: Re-Evaluation ────────────────────────────────────────────
    print("[Loop Controller] Generating v2 summary...")
    optimized_summary = summarize_research(optimized_report)
    
    print("[Loop Controller] Re-evaluating improved v2 report...")
    optimized_critique = critique_research(optimized_report, optimized_summary)
    
    if "error" in optimized_critique:
        print("[Loop Controller Error] Critic Agent failed on v2. Falling back to v1.")
        return _fallback_result(initial_report, initial_summary, initial_critique)
        
    optimized_score = float(optimized_critique.get("score", 0.0))
    score_delta = round(optimized_score - initial_score, 1)
    
    print(f"\n[Loop Controller] Refinement Complete!")
    print(f"Original Score: {initial_score} | New Score: {optimized_score} | Delta: {score_delta}")
    
    # ── Step 4: Decision Logic ───────────────────────────────────────────
    if optimized_score > initial_score:
        print("[Loop Controller] Optimization successful. Retaining v2.")
        return {
            "final_report": optimized_report,
            "original_report": initial_report,
            "final_summary": optimized_summary,
            "final_critique": optimized_critique,
            "original_critique": initial_critique,
            "optimized": True,
            "score_delta": score_delta
        }
    else:
        print("[Loop Controller] Refinement did not improve quality. Falling back to v1.")
        return {
            "final_report": initial_report,
            "original_report": initial_report,
            "final_summary": initial_summary,
            "final_critique": initial_critique,
            "original_critique": initial_critique,
            "optimized": False,
            "score_delta": score_delta
        }


def _fallback_result(report, summary, critique):
    """Helper to safely format a fallback return package."""
    return {
        "final_report": report,
        "original_report": report,
        "final_summary": summary,
        "final_critique": critique,
        "original_critique": critique,
        "optimized": False,
        "score_delta": 0.0
    }
